apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetdockerdemo
  labels:
    app: aspnetdockerdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetdockerdemo
  template:
    metadata:
      labels:
        app: aspnetdockerdemo
    spec:
      containers:
        - name: #{ContainerName}#
          image: #{ContainerName}#.azurecr.io/#{RepositoryName}#:#{Build.BuildId}#  
          imagePullPolicy: Always      
          imagePullSecrets:
            - name: #{PullSecretKey}#
          ports:
            - name: http
              containerPort: 89
              protocol: TCP
          nodeSelector:
            beta.kubernetes.io/os: windows
            kubernetes.io/role: agent
            type: virtual-kubelet
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: aspnetdockerdemo
  name: aspnetdockerdemo-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
     k8s-app: aspnetdockerdemo
  app: aspnetdockerdemo